server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8010
    timeout: 1s
data:
  database:
    dsn: "root:zhiguogg@tcp(81.69.46.111:3306)/realworld?charset=utf8mb4&parseTime=True&loc=Local"
